In [48]:
import pandas as pd

# Loading the Dataset

In [28]:
df = pd.read_csv("jackets.csv")

In [29]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,19014822,mothercare,Boys Colourblocked Fleece Lined Padded Jacket,4.6,7,3499.0,45.0,"""₹2,624.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Kap███s R███il █████████,"[{""size"":""3-6M"",""value"":""21.3in"",""value_name"":...",NaN,"D-1███PHA███8B,█████████L A███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
1,19015560,U.S. Polo Assn. Kids,Boys Yellow Solid Puffer Jacket,4.5,40,2499.0,43.0,"""₹1,424.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
2,19020502,U.S. Polo Assn.,Men Red & Navy Blue Colourblocked Puffer Jacket,4.4,338,6299.0,53.0,"""₹2,960.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":17,""2_stars"":7,""3_stars"":14,""4_stars...","[{""percentage"":""71"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
3,19014828,mothercare,Infant Girls Pure Cotton Tailored Jacket,4.5,15,2999.0,25.0,"""₹2,249.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Kap███s R███il █████████,"[{""size"":""Newborn"",""value"":""11.8in"",""value_nam...",NaN,"D-1███PHA███8B,█████████L A███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
4,18976038,VOXATI,Men Olive Green Denim Jacket,3.9,345,2599.0,58.0,"""₹1,090.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":51,""2_stars"":17,""3_stars"":27,""4_star...","[{""percentage"":""52"",""value_name"":""Fit, Just Ri...",VOX███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",NaN,Fir███Flo███ 27█████████ Ku███████████████████...,"[{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
5,19015652,U.S. Polo Assn. Kids,Girls Pink Self Design Bomber Jacket,4.2,19,2799.0,46.0,"""₹1,511.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
6,19020536,U.S. Polo Assn.,U S Polo Assn Men Blue & White Colourblocked L...,4.1,91,6999.0,50.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":10,""2_stars"":5,""3_stars"":5,""4_stars""...","[{""percentage"":""60"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020536_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
7,19020616,U.S. Polo Assn.,U S Polo Assn Men Beige & Black Colourblocked ...,4.3,47,6299.0,30.0,"""₹3,149.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":5,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
8,19020478,U.S. Polo Assn.,Men Black & Teal Green Colourblocked Sleeveles...,4.3,150,4599.0,40.0,"""₹2,759.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":14,""2_stars"":1,""3_stars"":5,""4_stars""...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
9,19002890,VERO AMORE,Women Pink Insulator Outdoor Parka Jacket Plus...,0.0,0,3850.0,59.0,"""₹1,578.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,AMR███WEA███G F█████████,"[{""size"":""3XL"",""value"":""48.0in"",""value_name"":""...",NaN,"172███REE███AGA█████████NA,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
10,19020722,U.S. Polo Assn.,Men Yellow Solid Puffer Jacket,4.0,64,5999.0,50.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":11,""2_stars"":2,""3_stars"":3,""4_stars""...","[{""percentage"":""29"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
11,19837040,High Star,Women Olive Green Solid Crop Padded Jacket,4.1,41,3749.0,85.0,"""₹3,749.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
12,19837008,High Star,Women Navy Blue Solid Parka Jacket,3.9,32,4549.0,85.0,"""₹4,549.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":5,""2_stars"":2,""3_stars"":2,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
13,19020654,U.S. Polo Assn.,U S Polo Assn Men Black And Blue Colourblocked...,4.0,54,6999.0,40.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
14,14991614,Roadster,Men Green Brand Logo Detail Tailored Jacket,4.2,363,1699.0,50.0,"""₹509.00""",INR,http://assets.myntassets.com/assets/images/149...,...,"{""1_star"":29,""2_stars"":11,""3_stars"":34,""4_star...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",GAR███CRY███S L█████████,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""C...","[""rw-14991614_cae700"",""https://videos.myntasse...","123███, K███ANW█████████hne█████████████████████",NaN,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
15,16182066,People,Men Mustard Sleeveless Bomber Jacket,4.3,71,1799.0,48.0,"""₹935.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":8,""4_stars"":...","[{""percentage"":""25"",""value_name"":""Fit, Tight""}...",Wes███ry ███din█████████d_P████████████,"[{""size"":""XS"",""value"":""39.0in"",""value_name"":""C...",NaN,Wes███ry ███din█████████e L███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
16,16175148,Status Quo,Men Black Colourblocked Padded Jacket,0.0,0,4999.0,50.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",CRA███CLO███NG █████████RIV████████████,"[{""size"":""M"",""value"":""21.0in"",""value_name"":""Ch...",NaN,2 S███EY ███ VI█████████GAN███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
17,19231126,Mast & Harbour,Women Brown PU Coated Biker Jacket,4.2,31,4499.0,68.0,"""₹1,439.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
18,14979464,Yuuki,Men Grey Melange and Black Colourblocked Light...,0.0,0,2199.0,55.0,"""₹989.00""",INR,http://assets.myntassets.com/assets/images/149...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,GUR███PA ███EST█████████NY,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...",NaN,"Plo███o. ███,Se█████████,UD███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
19,19987190,Peter England,Men White Solid Padded Jacket,3.9,33,2499.0,26.0,"""₹1,849.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""40.0in"",""value_name"":""Ch...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
20,19020564,U.S. Polo Assn.,Men Olive Green Bomber Jacket,4.3,112,5299.0,50.0,"""₹2,649.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":12,""2_stars"":0,""3_stars"":4,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
21,19015534,U.S. Polo Assn. Kids,Girls Maroon Solid Puffer Jacket,4.1,33,2499.0,36.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":5,""4_stars"":...",NaN,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
22,19020450,U.S. Polo Assn.,U S Polo Assn Men Navy Blue Puffer Jacket,4.3,96,6499.0,40.0,"""₹3,249.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":6,""2_stars"":5,""3_stars"":5,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
23,19020572,U.S. Polo Assn.,U S Polo Assn Men Olive Green Brand Logo Print...,4.0,95,5499.0,40.0,"""₹2,749.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":12,""2_stars"":3,""3_stars"":6,""4_stars""...","[{""percentage"":""56"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
24,14281506,HRX by Hrithik Roshan,HRX By Hrithik Roshan Lifestyle Men Medieval B...,3.9,127,3299.0,NaN,"""₹3,299.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":19,""2_stars"":7,""3_stars"":10,""4_stars...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
25,11973216,Mast & Harbour,Women Navy Blue Solid Hooded Lightweight Bombe...,4.0,378,2699.0,55.0,"""₹2,699.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":38,""2_stars"":17,""3_stars"":41,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-11973216_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
26,19020676,U.S. Polo Assn.,Men Charcoal Bomber Jacket,4.6,85,5699.0,45.0,"""₹3,134.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""92"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020676_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
27,19020358,U.S. Polo Assn.,Men Navy Blue Bomber Jacket,3.5,125,5799.0,50.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":31,""2_stars"":8,""3_stars"":9,""4_stars""...","[{""percentage"":""60"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020358_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
28,19020568,U.S. Polo Assn.,Men White Navy Blue Solid Reversible Open Fron...,4.2,199,6999.0,40.0,"""₹4,199.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":24,""2_stars"":5,""3_stars"":13,""4_stars...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets

# Display First 5 Rows

In [30]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,19014822,mothercare,Boys Colourblocked Fleece Lined Padded Jacket,4.6,7,3499.0,45.0,"""₹2,624.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Kap███s R███il █████████,"[{""size"":""3-6M"",""value"":""21.3in"",""value_name"":...",NaN,"D-1███PHA███8B,█████████L A███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
1,19015560,U.S. Polo Assn. Kids,Boys Yellow Solid Puffer Jacket,4.5,40,2499.0,43.0,"""₹1,424.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
2,19020502,U.S. Polo Assn.,Men Red & Navy Blue Colourblocked Puffer Jacket,4.4,338,6299.0,53.0,"""₹2,960.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":17,""2_stars"":7,""3_stars"":14,""4_stars...","[{""percentage"":""71"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
3,19014828,mothercare,Infant Girls Pure Cotton Tailored Jacket,4.5,15,2999.0,25.0,"""₹2,249.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Kap███s R███il █████████,"[{""size"":""Newborn"",""value"":""11.8in"",""value_nam...",NaN,"D-1███PHA███8B,█████████L A███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
4,18976038,VOXATI,Men Olive Green Denim Jacket,3.9,345,2599.0,58.0,"""₹1,090.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":51,""2_stars"":17,""3_stars"":27,""4_star...","[{""percentage"":""52"",""value_name"":""Fit, Just Ri...",VOX███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",NaN,Fir███Flo███ 27█████████ Ku███████████████████...,"[{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets

# Display Last 5 Rows

In [31]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
24,14281506,HRX by Hrithik Roshan,HRX By Hrithik Roshan Lifestyle Men Medieval B...,3.9,127,3299.0,NaN,"""₹3,299.00""",INR,http://assets.myntassets.com/assets/images/142...,...,"{""1_star"":19,""2_stars"":7,""3_stars"":10,""4_stars...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
25,11973216,Mast & Harbour,Women Navy Blue Solid Hooded Lightweight Bombe...,4.0,378,2699.0,55.0,"""₹2,699.00""",INR,http://assets.myntassets.com/assets/images/119...,...,"{""1_star"":38,""2_stars"":17,""3_stars"":41,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-11973216_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets
26,19020676,U.S. Polo Assn.,Men Charcoal Bomber Jacket,4.6,85,5699.0,45.0,"""₹3,134.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""92"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020676_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
27,19020358,U.S. Polo Assn.,Men Navy Blue Bomber Jacket,3.5,125,5799.0,50.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":31,""2_stars"":8,""3_stars"":9,""4_stars""...","[{""percentage"":""60"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020358_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets
28,19020568,U.S. Polo Assn.,Men White Navy Blue Solid Reversible Open Fron...,4.2,199,6999.0,40.0,"""₹4,199.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":24,""2_stars"":5,""3_stars"":13,""4_stars...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets

# Checking Dataset Shape

In [32]:
df.shape

(29, 24)

# Viewing Column Names

In [33]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

# Checking Data Types

In [34]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

# Dataset Information

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              29 non-null     int64
 1   title                   29 non-null     object
 2   product_description     29 non-null     object
 3   rating                  29 non-null     float64
 4   ratings_count           29 non-null     int64
 5   initial_price           29 non-null     float64
 6   discount                28 non-null     float64
 7   final_price             29 non-null     object
 8   currency                29 non-null     object
 9   images                  29 non-null     object
 10  delivery_options        29 non-null     object
 11  product_details         29 non-null     object
 12  breadcrumbs             29 non-null     object
 13  product_specifications  29 non-null     object
 14  amount_of_stars         29 non-null     object
 15  what_customers_said     22 non-null     object
 16  seller_name             25 non-null     object
 17  sizes                   29 non-null     object
 18  videos                  8 non-null      object
 19  seller_information      25 non-null     object
 20  variations              7 non-null      object
 21  best_offer              29 non-null     object
 22  more_offers             29 non-null     object
 23  category                29 non-null     object
dtypes: float64(3), int64(2), object(19)
memory usage: 5.6+ KB

# Checking Missing Values

In [36]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   1
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        7
seller_name                4
sizes                      0
videos                    21
seller_information         4
variations                22
best_offer                 0
more_offers                0
category                   0
dtype: int64

# Handling Missing Values

In [37]:
df['discount'] = df['discount'].fillna(0)

df['what_customers_said'] = df['what_customers_said'].fillna("No Review")

df['seller_name'] = df['seller_name'].fillna("Unknown Seller")

df['videos'] = df['videos'].fillna("No Video")

df['seller_information'] = df['seller_information'].fillna("No Information")

df['variations'] = df['variations'].fillna("No Variation")

# Verifying Missing Values Again

In [38]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

# Checking Duplicate Rows

In [39]:
df.duplicated().sum()

np.int64(0)

# Removing Duplicate Rows

In [40]:
df = df.drop_duplicates()

# Selecting Important Columns

In [41]:
df[['title', 'rating', 'final_price']].head()

                  title  rating  final_price
0            mothercare     4.6  "₹2,624.00"
1  U.S. Polo Assn. Kids     4.5  "₹1,424.00"
2       U.S. Polo Assn.     4.4  "₹2,960.00"
3            mothercare     4.5  "₹2,249.00"
4                VOXATI     3.9  "₹1,090.00"

# Filtering Expensive Jackets

In [49]:
expensive_jackets = df[df['initial_price'] > 5000]

expensive_jackets[['title', 'initial_price', 'final_price']]

              title  initial_price  final_price
2   U.S. Polo Assn.         6299.0       2960.0
6   U.S. Polo Assn.         6999.0       3499.0
7   U.S. Polo Assn.         6299.0       3149.0
10  U.S. Polo Assn.         5999.0       2999.0
13  U.S. Polo Assn.         6999.0       3499.0
20  U.S. Polo Assn.         5299.0       2649.0
22  U.S. Polo Assn.         6499.0       3249.0
23  U.S. Polo Assn.         5499.0       2749.0
26  U.S. Polo Assn.         5699.0       3134.0
27  U.S. Polo Assn.         5799.0       2899.0
28  U.S. Polo Assn.         6999.0       4199.0

# Cleaning final_price Column

In [50]:
df['final_price'] = df['final_price'].replace('[₹,"]', '', regex=True)

df['final_price'] = df['final_price'].astype(float)

# Creating Derived Column

In [51]:
df['price_difference'] = df['initial_price'] - df['final_price']

# Displaying Derived Column

In [52]:
df[['initial_price', 'final_price', 'price_difference']].tail()

    initial_price  final_price  price_difference
24         3299.0       3299.0               0.0
25         2699.0       2699.0               0.0
26         5699.0       3134.0            2565.0
27         5799.0       2899.0            2900.0
28         6999.0       4199.0            2800.0

In [53]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,price_difference
0,19014822,mothercare,Boys Colourblocked Fleece Lined Padded Jacket,4.6,7,3499.0,45.0,2624.0,INR,http://assets.myntassets.com/assets/images/190...,...,No Review,Kap███s R███il █████████,"[{""size"":""3-6M"",""value"":""21.3in"",""value_name"":...",No Video,"D-1███PHA███8B,█████████L A███████████████████...",No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,875.0
1,19015560,U.S. Polo Assn. Kids,Boys Yellow Solid Puffer Jacket,4.5,40,2499.0,43.0,1424.0,INR,http://assets.myntassets.com/assets/images/190...,...,No Review,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1075.0
2,19020502,U.S. Polo Assn.,Men Red & Navy Blue Colourblocked Puffer Jacket,4.4,338,6299.0,53.0,2960.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""71"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3339.0
3,19014828,mothercare,Infant Girls Pure Cotton Tailored Jacket,4.5,15,2999.0,25.0,2249.0,INR,http://assets.myntassets.com/assets/images/190...,...,No Review,Kap███s R███il █████████,"[{""size"":""Newborn"",""value"":""11.8in"",""value_nam...",No Video,"D-1███PHA███8B,█████████L A███████████████████...",No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,750.0
4,18976038,VOXATI,Men Olive Green Denim Jacket,3.9,345,2599.0,58.0,1090.0,INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""52"",""value_name"":""Fit, Just Ri...",VOX███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",No Video,Fir███Flo███ 27█████████ Ku███████████████████...,"[{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1509.0
5,19015652,U.S. Polo Assn. Kids,Girls Pink Self Design Bomber Jacket,4.2,19,2799.0,46.0,1511.0,INR,http://assets.myntassets.com/assets/images/190...,...,No Review,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1288.0
6,19020536,U.S. Polo Assn.,U S Polo Assn Men Blue & White Colourblocked L...,4.1,91,6999.0,50.0,3499.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""60"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020536_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3500.0
7,19020616,U.S. Polo Assn.,U S Polo Assn Men Beige & Black Colourblocked ...,4.3,47,6299.0,30.0,3149.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3150.0
8,19020478,U.S. Polo Assn.,Men Black & Teal Green Colourblocked Sleeveles...,4.3,150,4599.0,40.0,2759.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,Plo███o- ███ 1s█████████Sui███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1840.0
9,19002890,VERO AMORE,Women Pink Insulator Outdoor Parka Jacket Plus...,0.0,0,3850.0,59.0,1578.0,INR,http://assets.myntassets.com/assets/images/190...,...,No Review,AMR███WEA███G F█████████,"[{""size"":""3XL"",""value"":""48.0in"",""value_name"":""...",No Video,"172███REE███AGA█████████NA,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2272.0
10,19020722,U.S. Polo Assn.,Men Yellow Solid Puffer Jacket,4.0,64,5999.0,50.0,2999.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""29"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3000.0
11,19837040,High Star,Women Olive Green Solid Crop Padded Jacket,4.1,41,3749.0,85.0,3749.0,INR,http://assets.myntassets.com/assets/images/198...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",No Video,No Information,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets,0.0
12,19837008,High Star,Women Navy Blue Solid Parka Jacket,3.9,32,4549.0,85.0,4549.0,INR,http://assets.myntassets.com/assets/images/198...,...,"[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Bu...",No Video,No Information,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets,0.0
13,19020654,U.S. Polo Assn.,U S Polo Assn Men Black And Blue Colourblocked...,4.0,54,6999.0,40.0,3499.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3500.0
14,14991614,Roadster,Men Green Brand Logo Detail Tailored Jacket,4.2,363,1699.0,50.0,509.0,INR,http://assets.myntassets.com/assets/images/149...,...,"[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",GAR███CRY███S L█████████,"[{""size"":""XS"",""value"":""40.0in"",""value_name"":""C...","[""rw-14991614_cae700"",""https://videos.myntasse...","123███, K███ANW█████████hne█████████████████████",No Variation,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1190.0
15,16182066,People,Men Mustard Sleeveless Bomber Jacket,4.3,71,1799.0,48.0,935.0,INR,http://assets.myntassets.com/assets/images/161...,...,"[{""percentage"":""25"",""value_name"":""Fit, Tight""}...",Wes███ry ███din█████████d_P████████████,"[{""size"":""XS"",""value"":""39.0in"",""value_name"":""C...",No Video,Wes███ry ███din█████████e L███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,864.0
16,16175148,Status Quo,Men Black Colourblocked Padded Jacket,0.0,0,4999.0,50.0,2499.0,INR,http://assets.myntassets.com/assets/images/161...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",CRA███CLO███NG █████████RIV████████████,"[{""size"":""M"",""value"":""21.0in"",""value_name"":""Ch...",No Video,2 S███EY ███ VI█████████GAN███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2500.0
17,19231126,Mast & Harbour,Women Brown PU Coated Biker Jacket,4.2,31,4499.0,68.0,1439.0,INR,http://assets.myntassets.com/assets/images/192...,...,"[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",Sho███o. ███-10█████████enu███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3060.0
18,14979464,Yuuki,Men Grey Melange and Black Colourblocked Light...,0.0,0,2199.0,55.0,989.0,INR,http://assets.myntassets.com/assets/images/149...,...,No Review,GUR███PA ███EST█████████NY,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...",No Video,"Plo███o. ███,Se█████████,UD███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,1210.0
19,19987190,Peter England,Men White Solid Padded Jacket,3.9,33,2499.0,26.0,1849.0,INR,http://assets.myntassets.com/assets/images/199...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""40.0in"",""value_name"":""Ch...",No Video,"Gro███ Fl███, N█████████old███████████████████...",No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,650.0
20,19020564,U.S. Polo Assn.,Men Olive Green Bomber Jacket,4.3,112,5299.0,50.0,2649.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2650.0
21,19015534,U.S. Polo Assn. Kids,Girls Maroon Solid Puffer Jacket,4.1,33,2499.0,36.0,1599.0,INR,http://assets.myntassets.com/assets/images/190...,...,No Review,ARV███ LI███TYL█████████LIM██████,"[{""size"":""1-2Y"",""value"":""23.23in"",""value_name""...","[""https://videos.myntassets.com/assets/videos/...",10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,900.0
22,19020450,U.S. Polo Assn.,U S Polo Assn Men Navy Blue Puffer Jacket,4.3,96,6499.0,40.0,3249.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,3250.0
23,19020572,U.S. Polo Assn.,U S Polo Assn Men Olive Green Brand Logo Print...,4.0,95,5499.0,40.0,2749.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""56"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2750.0
24,14281506,HRX by Hrithik Roshan,HRX By Hrithik Roshan Lifestyle Men Medieval B...,3.9,127,3299.0,0.0,3299.0,INR,http://assets.myntassets.com/assets/images/142...,...,"[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Ch...",No Video,No Information,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets,0.0
25,11973216,Mast & Harbour,Women Navy Blue Solid Hooded Lightweight Bombe...,4.0,378,2699.0,55.0,2699.0,INR,http://assets.myntassets.com/assets/images/119...,...,"[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-11973216_cae700"",""https://videos.myntasse...",No Information,No Variation,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jackets,0.0
26,19020676,U.S. Polo Assn.,Men Charcoal Bomber Jacket,4.6,85,5699.0,45.0,3134.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""92"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020676_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2565.0
27,19020358,U.S. Polo Assn.,Men Navy Blue Bomber Jacket,3.5,125,5799.0,50.0,2899.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""60"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-19020358_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,No Variation,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2900.0
28,19020568,U.S. Polo Assn.,Men White Navy Blue Solid Reversible Open Fron...,4.2,199,6999.0,40.0,4199.0,INR,http://assets.myntassets.com/assets/images/190...,...,"[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",No Video,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Purchase of 2 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",jackets,2800.0

# Saving Cleaned Dataset

In [55]:
df.to_csv("cleaned_jackets.csv", index=False)

print("Saved successfully!")

Saved successfully!

# Brief Summary

In this project, I worked with the jackets.csv dataset using the Pandas library in Python. First, I loaded the dataset into a DataFrame and explored it using functions like head(), tail(), shape, columns, dtypes, and info() to understand the dataset properly.

After exploring the data, I checked for missing values using isnull().sum() and handled them using fillna() by replacing null values with suitable values such as 0, "No Review", "Unknown Seller", and "No Video". I also checked for duplicate rows and removed them from the dataset.

Next, I performed some basic data operations like selecting important columns and filtering expensive jackets with initial prices greater than 5000. I then cleaned the final_price column by removing currency symbols and commas and converted it into float datatype for calculations.

To create a derived column, I calculated price_difference using the initial_price and final_price columns. Finally, I saved the cleaned dataset as cleaned_jackets.csv for future analysis and use.